# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

include ../../../Makefile.shared-python

COMPONENT_NAME := geti-controller
DOCKER_BUILD_CONTEXT := --build-context libs=../../../libs

static-code-analysis:
	@echo "Not applicable"

test-component:
	@echo "Not applicable"

test-integration:
	@echo "Not applicable"
