{
 "title": "Modelmesh Monitoring Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Infer API Requests Per Second (5m Avg) Per ModelMesh Container ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(modelmesh_api_request_milliseconds_count[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(modelmesh_api_request_milliseconds_sum[5m])/rate(modelmesh_api_request_milliseconds_count[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Model Infer API Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(modelmesh_api_request_milliseconds_count[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "All ModelMesh Model Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modelmesh_models_managed_total", "legendFormat": "Managed" },
    { "expr": "modelmesh_models_loaded_total", "legendFormat": "Loaded" }
   ]
  },
  {
   "title": "Serving Runtime Cache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(modelmesh_instance_used_bytes/1024)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(modelmesh_instance_capacity_bytes/1024)",
     "legendFormat": "Total Cache Capacity"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "rate(modelmesh_cache_miss_milliseconds_count[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Models on Serving Runtime",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modelmesh_instance_models_total{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Serving Runtime Model Loading/Unloading Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 7, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(modelmesh_loadmodel_milliseconds_count[5m]))",
     "legendFormat": "Load"
    },
    {
     "expr": "sum(rate(modelmesh_unloadmodel_milliseconds_count[5m]))*-1",
     "legendFormat": "Unload(-)"
    }
   ]
  },
  {
   "title": " Loaded Models Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(modelmesh_loaded_model_size_bytes_sum[5m]))"
    }
   ]
  }
 ]
}