include ../Makefile.shared-workflows

build-image:
	@echo "Nothing to do - ${COMPONENT_NAME} does not have an image to build"

publish-image:
	@echo "Nothing to do - ${COMPONENT_NAME} does not have an image to push"