// Copyright (C) 2022-2025 Intel Corporation
// LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

import { RESOURCE_TYPE, USER_ROLE } from '@geti/core/src/users/users.interface';

import { OPERATION, OperationPermission, OperationPermissionOld } from './has-permission.interface';

const ORGANIZATION_ADMIN_PERMISSION = {
    role: USER_ROLE.ORGANIZATION_ADMIN,
    resourceType: RESOURCE_TYPE.ORGANIZATION,
};

const WORKSPACE_ADMIN_PERMISSION = {
    role: USER_ROLE.WORKSPACE_ADMIN,
    resourceType: RESOURCE_TYPE.WORKSPACE,
};

const WORKSPACE_CONTRIBUTOR_PERMISSION = {
    role: USER_ROLE.WORKSPACE_CONTRIBUTOR,
    resourceType: RESOURCE_TYPE.WORKSPACE,
};

const PROJECT_MANAGER_PERMISSION = {
    role: USER_ROLE.PROJECT_MANAGER,
    resourceType: RESOURCE_TYPE.PROJECT,
};

const PROJECT_CONTRIBUTOR_PERMISSION = {
    role: USER_ROLE.PROJECT_CONTRIBUTOR,
    resourceType: RESOURCE_TYPE.PROJECT,
};

const ORGANIZATION_CONTRIBUTION_PERMISSION = {
    role: USER_ROLE.ORGANIZATION_CONTRIBUTOR,
    resourceType: RESOURCE_TYPE.ORGANIZATION,
};

export const OPERATION_PERMISSION: OperationPermission = {
    [OPERATION.ADD_USER_TO_PROJECT]: [WORKSPACE_ADMIN_PERMISSION, PROJECT_MANAGER_PERMISSION],
    [OPERATION.ADD_USER_TO_WORKSPACE]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
    [OPERATION.ANALYTICS_TAB]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
    [OPERATION.CAN_SEE_PROJECT]: [PROJECT_MANAGER_PERMISSION, PROJECT_CONTRIBUTOR_PERMISSION],
    [OPERATION.CAN_SEE_WORKSPACE]: [
        ORGANIZATION_ADMIN_PERMISSION,
        WORKSPACE_ADMIN_PERMISSION,
        WORKSPACE_CONTRIBUTOR_PERMISSION,
    ],
    [OPERATION.CAN_VIEW_CREDITS_USAGE]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
    [OPERATION.IMPORT_PROJECT]: [WORKSPACE_ADMIN_PERMISSION, WORKSPACE_CONTRIBUTOR_PERMISSION],
    [OPERATION.INVITE_USER]: [ORGANIZATION_ADMIN_PERMISSION],
    [OPERATION.MANAGE_USER]: [ORGANIZATION_ADMIN_PERMISSION],
    [OPERATION.PROJECT_CREATION]: [WORKSPACE_ADMIN_PERMISSION, WORKSPACE_CONTRIBUTOR_PERMISSION],
    [OPERATION.PROJECT_DELETION]: [WORKSPACE_ADMIN_PERMISSION, PROJECT_MANAGER_PERMISSION],
    [OPERATION.PROJECT_NAME_EDITION]: [WORKSPACE_ADMIN_PERMISSION, PROJECT_MANAGER_PERMISSION],
    [OPERATION.USAGE_TAB]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
    [OPERATION.WORKSPACE_CREATION]: [ORGANIZATION_ADMIN_PERMISSION, ORGANIZATION_CONTRIBUTION_PERMISSION],
    [OPERATION.WORKSPACE_MANAGEMENT]: [WORKSPACE_ADMIN_PERMISSION],
    [OPERATION.PLATFORM_UPGRADE]: [ORGANIZATION_ADMIN_PERMISSION],
};

const canManageProject = [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION, PROJECT_MANAGER_PERMISSION];
const canCreateProject = [WORKSPACE_ADMIN_PERMISSION, WORKSPACE_CONTRIBUTOR_PERMISSION];

export const OPERATION_PERMISSION_OLD: OperationPermissionOld = {
    [OPERATION.INVITE_USER]: [ORGANIZATION_ADMIN_PERMISSION],
    [OPERATION.MANAGE_USER]: [ORGANIZATION_ADMIN_PERMISSION],
    [OPERATION.WORKSPACE_MANAGEMENT]: [WORKSPACE_ADMIN_PERMISSION],
    [OPERATION.IMPORT_PROJECT]: [WORKSPACE_ADMIN_PERMISSION],
    [OPERATION.ADD_USER_TO_PROJECT]: canManageProject,
    [OPERATION.PROJECT_CREATION]: canCreateProject,
    [OPERATION.PROJECT_DELETION]: canManageProject,
    [OPERATION.CAN_VIEW_CREDITS_USAGE]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
    [OPERATION.PROJECT_NAME_EDITION]: [WORKSPACE_ADMIN_PERMISSION, PROJECT_MANAGER_PERMISSION],
    [OPERATION.USAGE_TAB]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
    [OPERATION.ANALYTICS_TAB]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
    [OPERATION.PLATFORM_UPGRADE]: [ORGANIZATION_ADMIN_PERMISSION],
};
