apiVersion: v2
name: control-plane
description: control plane deployment
version: 0.1.1
appVersion: v0.0.1
dependencies:
  - name: account-service
    version: 0.0.2
    condition: enabled.account-service
  - name: onboarding-service
    version: 0.0.1
    condition: enabled.onboarding-service
  - name: notifier
    version: 0.0.1
    condition: enabled.notifier
  - name: credit-system
    version: 0.1.0
    condition: enabled.credit-system
  - name: auth-proxy
    version: 0.1.0
    condition: enabled.auth-proxy
  - name: control-plane-common
    version: 0.0.1
  - name: initial-user
    version: 0.0.1
    condition: enabled.initial-user

