include ../../../Makefile.shared-python

COMPONENT_NAME := modelregistration
DOCKER_BUILD_CONTEXT := --build-context libs=../../../libs \

# TODO CVS-165596 remove this target after fixing the stylechecks
static-code-analysis:
	-$(MAKE)  static-code-analysis-default
	true

