global:
  enable_local_image_pull_secret: ""
  kafka_topic_prefix: ""
  kubectl:
    registry: docker.io
    repository: alpine
    name: k8s:1.31.12
  busybox:
    registry: quay.io
    repository: prometheus
    name: busybox:glibc

## Service parameters
##
service:
  ## @param service.ports.client Kafka svc port for client connections
  ##
  ports:
    client: 9092

## @section Common parameters
## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""


## @section Kafka parameters

## ref: https://hub.docker.com/r/apache/kafka/tags
## @param image.registry Kafka image registry
## @param image.repository Kafka image repository
## @param image.tag Kafka image tag (immutable tags are recommended)
## @param image.pullPolicy Kafka image pull policy
## @param image.pullSecrets Specify docker-registry secret names as an array
## @param image.debug Specify if debug values should be set
##
image:
  registry: docker.io
  repository: apache
  name: kafka:4.1.0
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
      - ALL

## @section Kafka provisioning parameters

## Kafka provisioning
##
provisioning:
  kafkaHost: impt-kafka
  ## @param provisioning.numPartitions Default number of partitions for topics when unspecified
  ##
  numPartitions: 1
  ## @param provisioning.replicationFactor Default replication factor for topics when unspecified
  ##
  replicationFactor: 1
  ## @param provisioning.topics Kafka provisioning topics
  ## - name: topic-name
  ##   partitions: 1
  ##   replicationFactor: 1
  ##   ## https://kafka.apache.org/documentation/#topicconfigs
  ##   config:
  ##     max.message.bytes: 64000
  ##     flush.messages: 1
  ##
  topics:
    - name: annotation_scenes_to_revisit
      config: []
    - name: configuration_changes
      config: []
    - name: dataset_counters_updated
      config: []
    - name: dataset_updated
      config: []
    - name: training_successful
      config: []
    - name: media_deletions
      config: []
    - name: media_preprocessing
      config: []
    - name: media_uploads
      config: []
    - name: new_annotation_scene
      config: []
    - name: predictions_and_metadata_created
      config: []
    - name: project_creations
      config: []
    - name: project_deletions
      config: []
    - name: project_updates
      config: []
    - name: thumbnail_video_missing
      config: []
    - name: model_activated
      config: []
    - name: model_reverted
      config: []
    - name: flyte_event
      config: []
    - name: job_step_details
      config: []
    - name: job_update
      config: []
    - name: on_job_cancelled
      config: []
    - name: on_job_failed
      config: []
    - name: on_job_finished
      config: []
    - name: project_notifications
      config: []
    - name: credits_lease
      config: []

  ## @param provisioning.acls Provision Kafka ACL rules
  ##
  acls:
    # Jobs which run in Flyte use Flyte kafka credentials, therefore user in this case is "flyte"

    # annotation_scenes_to_revisit
    - user: director
      topic: annotation_scenes_to_revisit
      operations: ["Read"]
    - user: resource
      topic: annotation_scenes_to_revisit
      operations: ["Write"]

    # configuration_changes
    - user: director
      topic: configuration_changes
      operations: ["Read", "Write"]

    # dataset_counters_updated
    - user: director
      topic: dataset_counters_updated
      operations: ["Read", "Write"]

    # dataset_updated
    - user: director
      topic: dataset_updated
      operations: ["Read", "Write"]
    - user: flyte
      topic: dataset_updated
      operations: ["Write"]

    # training_successful
    - user: director
      topic: training_successful
      operations: ["Read", "Write"]
    - user: flyte
      topic: training_successful
      operations: ["Write"]

    # media_deletions
    - user: director
      topic: media_deletions
      operations: ["Read"]
    - user: resource
      topic: media_deletions
      operations: ["Write"]

    # media_uploads
    - user: director
      topic: media_uploads
      operations: ["Read"]
    - user: resource
      topic: media_uploads
      operations: ["Read"]
    - user: dataset-ie
      topic: media_uploads
      operations: ["Write"]
    - user: flyte
      topic: media_uploads
      operations: [ "Write" ]
    - user: resource
      topic: media_uploads
      operations: ["Write"]

    # media_preprocessing
    - user: resource
      topic: media_preprocessing
      operations: ["Read", "Write"]

    # new_annotation_scene
    - user: director
      topic: new_annotation_scene
      operations: ["Read"]
    - user: dataset-ie
      topic: new_annotation_scene
      operations: ["Write"]
    - user: flyte
      topic: new_annotation_scene
      operations: ["Write"]
    - user: resource
      topic: new_annotation_scene
      operations: ["Read", "Write"]

    # predictions_and_metadata_created
    - user: director
      topic: predictions_and_metadata_created
      operations: ["Read", "Write"]
    - user: flyte
      topic: predictions_and_metadata_created
      operations: ["Write"]

    # project_creations
    - user: director
      topic: project_creations
      operations: ["Read"]
    - user: dataset-ie
      topic: project_creations
      operations: ["Write"]
    - user: flyte
      topic: project_creations
      operations: [ "Write" ]
    - user: resource
      topic: project_creations
      operations: ["Write"]

    # project_deletions
    - user: director
      topic: project_deletions
      operations: ["Read"]
    - user: resource
      topic: project_deletions
      operations: ["Read", "Write"]
    - user: jobs-scheduler
      topic: project_deletions
      operations: ["Read"]
    - user: visual-prompt
      topic: project_deletions

    # project_updates
    - user: director
      topic: project_updates
      operations: ["Read"]
    - user: visual-prompt
      topic: project_updates
      operations: [ "Read" ]
    - user: resource
      topic: project_updates
      operations: ["Write"]

    # thumbnail_video_missing
    - user: resource
      topic: thumbnail_video_missing
      operations: ["Read", "Write"]

    # model_activated
    - user: director
      topic: model_activated
      operations: ["Read", "Write"]
    - user: resource
      topic: model_activated
      operations: ["Read", "Write"]
    - user: flyte
      topic: model_activated
      operations: ["Write"]

    # model_reverted
    - user: director
      topic: model_reverted
      operations: ["Read", "Write"]
    - user: resource
      topic: model_reverted
      operations: ["Write"]
    - user: flyte
      topic: model_reverted
      operations: ["Write"]

    # flyte_event
    - user: flyte
      topic: flyte_event
      operations: ["Read", "Write"]
    - user: jobs-scheduler
      topic: flyte_event
      operations: ["Read"]

    # job_step_details
    - user: flyte
      topic: job_step_details
      operations: ["Write"]
    - user: jobs-scheduler
      topic: job_step_details
      operations: ["Read"]

    # job_update
    - user: flyte
      topic: job_update
      operations: ["Write"]
    - user: jobs-scheduler
      topic: job_update
      operations: ["Read"]

    # on_job_cancelled
    - user: jobs-scheduler
      topic: on_job_cancelled
      operations: ["Read", "Write"]
    - user: director
      topic: on_job_cancelled
      operations: ["Read"]
    - user: dataset-ie
      topic: on_job_cancelled
      operations: ["Read"]

    # on_job_failed
    - user: jobs-scheduler
      topic: on_job_failed
      operations: ["Read", "Write"]
    - user: director
      topic: on_job_failed
      operations: ["Read"]

    # on_job_finished
    - user: jobs-scheduler
      topic: on_job_finished
      operations: ["Read", "Write"]
    - user: director
      topic: on_job_finished
      operations: ["Read"]
    - user: dataset-ie
      topic: on_job_finished
      operations: ["Read"]
    - user: project-ie
      topic: on_job_finished
      operations: ["Read"]

    # project_notifications
    - user: account-service
      topic: project_notifications
      operations: ["Read", "Write"]
    - user: notifier
      topic: project_notifications
      operations: ["Read"]
    - user: gateway
      topic: project_notifications
      operations: [ "Read", "Write" ]
    - user: user-directory
      topic: project_notifications
      operations: [ "Read", "Write" ]

    # credits_lease
    - user: jobs-scheduler
      topic: credits_lease
      operations: ["Write"]
    - user: credit-system
      topic: credits_lease
      operations: ["Read"]
