include ../Makefile.shared-workflows

COMPONENT_NAME       := train-job

DOCKER_BUILD_CONTEXT := --build-context common=../common \
						--build-context libs=../../../libs \
						--build-context iai_core=../../../interactive_ai/libs/iai_core_py \
						--build-context media_utils=../../../interactive_ai/libs/media_utils \
						--build-context supported_models=../../../interactive_ai/supported_models \
