include ../../../Makefile.shared-go

COMPONENT_NAME := inference-gateway

DOCKER_BUILD_CONTEXT := --build-context iai_core=$(CWD)/interactive_ai/libs/iai_core_go \
						--build-context modelmesh=$(CWD)/libs/grpc_interfaces/src/grpc_interfaces/model_mesh/go/pb \
						--build-context modelregistration=$(CWD)/libs/grpc_interfaces/src/grpc_interfaces/model_registration/go/pb \
						--build-context predict=$(CWD)/libs/grpc_interfaces/src/grpc_interfaces/predict/go/pb
DOCKER_IMAGE_DESCRIPTION := Inference Gateway for Geti
