include ../Makefile.shared-workflows

COMPONENT_NAME       := project-ie-job

DOCKER_BUILD_CONTEXT := --build-context common=../common \
						--build-context libs=../../../libs \
						--build-context iai_core=../../../interactive_ai/libs/iai_core_py \
						--build-context media_utils=../../../interactive_ai/libs/media_utils \
						--build-context data_migration=../../../interactive_ai/data_migration \
