# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

CWD = $(abspath $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST))))))
include $(CWD)/../../Makefile.shared

build-image:
	@echo "Building docker image for: ${BUILDER_IMAGE_NAME}"
	@echo ${DOCKER_EXTRA_ARGS}
	@docker build \
		${DOCKER_EXTRA_ARGS} \
		--label "org.opencontainers.image.description=${DOCKER_IMAGE_DESCRIPTION}" \
		-t ${IMAGES_REGISTRY}/builders/${BUILDER_IMAGE_NAME}:${BUILDER_TAG} \
		-f ./Dockerfile .

list-image:
	@echo ${IMAGES_REGISTRY}/builders/${BUILDER_IMAGE_NAME}:${BUILDER_TAG}

push-image:
	@echo "Pushing docker image: ${IMAGES_REGISTRY}/builders/${BUILDER_IMAGE_NAME}:${BUILDER_TAG}"
	@docker push ${IMAGES_REGISTRY}/builders/${BUILDER_IMAGE_NAME}:${BUILDER_TAG}

