// Copyright (C) 2022-2025 Intel Corporation
// LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: workspace.proto

package pb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkspaceData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ModifiedAt     *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	ModifiedBy     string                 `protobuf:"bytes,7,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	WorkspaceAdmin string                 `protobuf:"bytes,8,opt,name=workspace_admin,json=workspaceAdmin,proto3" json:"workspace_admin,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkspaceData) Reset() {
	*x = WorkspaceData{}
	mi := &file_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceData) ProtoMessage() {}

func (x *WorkspaceData) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceData.ProtoReflect.Descriptor instead.
func (*WorkspaceData) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *WorkspaceData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkspaceData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkspaceData) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *WorkspaceData) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkspaceData) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *WorkspaceData) GetModifiedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *WorkspaceData) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

func (x *WorkspaceData) GetWorkspaceAdmin() string {
	if x != nil {
		return x.WorkspaceAdmin
	}
	return ""
}

type WorkspaceIdRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkspaceIdRequest) Reset() {
	*x = WorkspaceIdRequest{}
	mi := &file_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceIdRequest) ProtoMessage() {}

func (x *WorkspaceIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceIdRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceIdRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *WorkspaceIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkspaceIdRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type FindWorkspaceRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId        string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	BillingChildAccountId string                 `protobuf:"bytes,3,opt,name=billing_child_account_id,json=billingChildAccountId,proto3" json:"billing_child_account_id,omitempty"`
	CreatedAtFrom         *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=created_at_from,json=createdAtFrom,proto3" json:"created_at_from,omitempty"`
	CreatedAtTo           *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=created_at_to,json=createdAtTo,proto3" json:"created_at_to,omitempty"`
	CreatedBy             string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ModifiedAtFrom        *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=modified_at_from,json=modifiedAtFrom,proto3" json:"modified_at_from,omitempty"`
	ModifiedAtTo          *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=modified_at_to,json=modifiedAtTo,proto3" json:"modified_at_to,omitempty"`
	ModifiedBy            string                 `protobuf:"bytes,9,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	Skip                  int32                  `protobuf:"varint,10,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit                 int32                  `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy                string                 `protobuf:"bytes,12,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`                      //attribute name
	SortDirection         string                 `protobuf:"bytes,13,opt,name=sort_direction,json=sortDirection,proto3" json:"sort_direction,omitempty"` //asc/desc
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FindWorkspaceRequest) Reset() {
	*x = FindWorkspaceRequest{}
	mi := &file_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindWorkspaceRequest) ProtoMessage() {}

func (x *FindWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*FindWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *FindWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindWorkspaceRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *FindWorkspaceRequest) GetBillingChildAccountId() string {
	if x != nil {
		return x.BillingChildAccountId
	}
	return ""
}

func (x *FindWorkspaceRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAtFrom
	}
	return nil
}

func (x *FindWorkspaceRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAtTo
	}
	return nil
}

func (x *FindWorkspaceRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *FindWorkspaceRequest) GetModifiedAtFrom() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAtFrom
	}
	return nil
}

func (x *FindWorkspaceRequest) GetModifiedAtTo() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAtTo
	}
	return nil
}

func (x *FindWorkspaceRequest) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

func (x *FindWorkspaceRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *FindWorkspaceRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindWorkspaceRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *FindWorkspaceRequest) GetSortDirection() string {
	if x != nil {
		return x.SortDirection
	}
	return ""
}

type ListWorkspacesResponse struct {
	state             protoimpl.MessageState           `protogen:"open.v1"`
	Workspaces        []*WorkspaceData                 `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	TotalCount        int32                            `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalMatchedCount int32                            `protobuf:"varint,3,opt,name=total_matched_count,json=totalMatchedCount,proto3" json:"total_matched_count,omitempty"`
	NextPage          *ListWorkspacesResponse_NextPage `protobuf:"bytes,4,opt,name=next_page,json=nextPage,proto3,oneof" json:"next_page,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*WorkspaceData {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *ListWorkspacesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListWorkspacesResponse) GetTotalMatchedCount() int32 {
	if x != nil {
		return x.TotalMatchedCount
	}
	return 0
}

func (x *ListWorkspacesResponse) GetNextPage() *ListWorkspacesResponse_NextPage {
	if x != nil {
		return x.NextPage
	}
	return nil
}

type ListWorkspacesResponse_NextPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          int32                  `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse_NextPage) Reset() {
	*x = ListWorkspacesResponse_NextPage{}
	mi := &file_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse_NextPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse_NextPage) ProtoMessage() {}

func (x *ListWorkspacesResponse_NextPage) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse_NextPage.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse_NextPage) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListWorkspacesResponse_NextPage) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListWorkspacesResponse_NextPage) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_workspace_proto protoreflect.FileDescriptor

const file_workspace_proto_rawDesc = "" +
	"\n" +
	"\x0fworkspace.proto\x12\tworkspace\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xbd\x02\n" +
	"\rWorkspaceData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12;\n" +
	"\vmodified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\x1f\n" +
	"\vmodified_by\x18\a \x01(\tR\n" +
	"modifiedBy\x12'\n" +
	"\x0fworkspace_admin\x18\b \x01(\tR\x0eworkspaceAdmin\"M\n" +
	"\x12WorkspaceIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"\xc2\x04\n" +
	"\x14FindWorkspaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x127\n" +
	"\x18billing_child_account_id\x18\x03 \x01(\tR\x15billingChildAccountId\x12B\n" +
	"\x0fcreated_at_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rcreatedAtFrom\x12>\n" +
	"\rcreated_at_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedAtTo\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x12D\n" +
	"\x10modified_at_from\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0emodifiedAtFrom\x12@\n" +
	"\x0emodified_at_to\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fmodifiedAtTo\x12\x1f\n" +
	"\vmodified_by\x18\t \x01(\tR\n" +
	"modifiedBy\x12\x12\n" +
	"\x04skip\x18\n" +
	" \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\v \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\f \x01(\tR\x06sortBy\x12%\n" +
	"\x0esort_direction\x18\r \x01(\tR\rsortDirection\"\xb5\x02\n" +
	"\x16ListWorkspacesResponse\x128\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x18.workspace.WorkspaceDataR\n" +
	"workspaces\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12.\n" +
	"\x13total_matched_count\x18\x03 \x01(\x05R\x11totalMatchedCount\x12L\n" +
	"\tnext_page\x18\x04 \x01(\v2*.workspace.ListWorkspacesResponse.NextPageH\x00R\bnextPage\x88\x01\x01\x1a4\n" +
	"\bNextPage\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limitB\f\n" +
	"\n" +
	"_next_page2\x9f\x05\n" +
	"\tWorkspace\x12{\n" +
	"\x06create\x12\x18.workspace.WorkspaceData\x1a\x18.workspace.WorkspaceData\"=\x82\xd3\xe4\x93\x027:\x01*\"2/api/v1/organizations/{organization_id}/workspaces\x12\x80\x01\n" +
	"\x06modify\x12\x18.workspace.WorkspaceData\x1a\x18.workspace.WorkspaceData\"B\x82\xd3\xe4\x93\x02<:\x01*\x1a7/api/v1/organizations/{organization_id}/workspaces/{id}\x12\x85\x01\n" +
	"\tget_by_id\x12\x1d.workspace.WorkspaceIdRequest\x1a\x18.workspace.WorkspaceData\"?\x82\xd3\xe4\x93\x029\x127/api/v1/organizations/{organization_id}/workspaces/{id}\x12\x86\x01\n" +
	"\x04find\x12\x1f.workspace.FindWorkspaceRequest\x1a!.workspace.ListWorkspacesResponse\":\x82\xd3\xe4\x93\x024\x122/api/v1/organizations/{organization_id}/workspaces\x12\x80\x01\n" +
	"\x06delete\x12\x1d.workspace.WorkspaceIdRequest\x1a\x16.google.protobuf.Empty\"?\x82\xd3\xe4\x93\x029*7/api/v1/organizations/{organization_id}/workspaces/{id}B\"Z geti.com/account_service_grpc/pbb\x06proto3"

var (
	file_workspace_proto_rawDescOnce sync.Once
	file_workspace_proto_rawDescData []byte
)

func file_workspace_proto_rawDescGZIP() []byte {
	file_workspace_proto_rawDescOnce.Do(func() {
		file_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_proto_rawDesc), len(file_workspace_proto_rawDesc)))
	})
	return file_workspace_proto_rawDescData
}

var file_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_workspace_proto_goTypes = []any{
	(*WorkspaceData)(nil),                   // 0: workspace.WorkspaceData
	(*WorkspaceIdRequest)(nil),              // 1: workspace.WorkspaceIdRequest
	(*FindWorkspaceRequest)(nil),            // 2: workspace.FindWorkspaceRequest
	(*ListWorkspacesResponse)(nil),          // 3: workspace.ListWorkspacesResponse
	(*ListWorkspacesResponse_NextPage)(nil), // 4: workspace.ListWorkspacesResponse.NextPage
	(*timestamp.Timestamp)(nil),             // 5: google.protobuf.Timestamp
	(*empty.Empty)(nil),                     // 6: google.protobuf.Empty
}
var file_workspace_proto_depIdxs = []int32{
	5,  // 0: workspace.WorkspaceData.created_at:type_name -> google.protobuf.Timestamp
	5,  // 1: workspace.WorkspaceData.modified_at:type_name -> google.protobuf.Timestamp
	5,  // 2: workspace.FindWorkspaceRequest.created_at_from:type_name -> google.protobuf.Timestamp
	5,  // 3: workspace.FindWorkspaceRequest.created_at_to:type_name -> google.protobuf.Timestamp
	5,  // 4: workspace.FindWorkspaceRequest.modified_at_from:type_name -> google.protobuf.Timestamp
	5,  // 5: workspace.FindWorkspaceRequest.modified_at_to:type_name -> google.protobuf.Timestamp
	0,  // 6: workspace.ListWorkspacesResponse.workspaces:type_name -> workspace.WorkspaceData
	4,  // 7: workspace.ListWorkspacesResponse.next_page:type_name -> workspace.ListWorkspacesResponse.NextPage
	0,  // 8: workspace.Workspace.create:input_type -> workspace.WorkspaceData
	0,  // 9: workspace.Workspace.modify:input_type -> workspace.WorkspaceData
	1,  // 10: workspace.Workspace.get_by_id:input_type -> workspace.WorkspaceIdRequest
	2,  // 11: workspace.Workspace.find:input_type -> workspace.FindWorkspaceRequest
	1,  // 12: workspace.Workspace.delete:input_type -> workspace.WorkspaceIdRequest
	0,  // 13: workspace.Workspace.create:output_type -> workspace.WorkspaceData
	0,  // 14: workspace.Workspace.modify:output_type -> workspace.WorkspaceData
	0,  // 15: workspace.Workspace.get_by_id:output_type -> workspace.WorkspaceData
	3,  // 16: workspace.Workspace.find:output_type -> workspace.ListWorkspacesResponse
	6,  // 17: workspace.Workspace.delete:output_type -> google.protobuf.Empty
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_workspace_proto_init() }
func file_workspace_proto_init() {
	if File_workspace_proto != nil {
		return
	}
	file_workspace_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_proto_rawDesc), len(file_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_proto_goTypes,
		DependencyIndexes: file_workspace_proto_depIdxs,
		MessageInfos:      file_workspace_proto_msgTypes,
	}.Build()
	File_workspace_proto = out.File
	file_workspace_proto_goTypes = nil
	file_workspace_proto_depIdxs = nil
}
