# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

include ../Makefile.shared-builders

BUILDER_IMAGE_NAME = go-builder
BUILDER_TAG = v1.1.0
DOCKER_IMAGE_DESCRIPTION := Go builder image for Geti
