# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

include ../../../Makefile.shared-go

COMPONENT_NAME := media-ms
DOCKER_BUILD_CONTEXT := --build-context iai_core=$(CWD)/interactive_ai/libs/iai_core_go
DOCKER_IMAGE_DESCRIPTION := Media Service for Geti
