task: detection
capabilities:
  tiling: true  # by default, all detection models support tiling (unless specified otherwise)

hyperparameters:
  dataset_preparation:
    augmentation:
      random_affine:
        enable: false
      random_horizontal_flip:
        enable: false
      random_vertical_flip:
        enable: false
      gaussian_blur:
        enable: false
      color_jitter:
        enable: false
      random_iou_crop:
        enable: false
      tiling:
        enable: false
        adaptive_tiling: false
        tile_size: 400
        tile_overlap: 0.2
  evaluation:
    metric: f_measure
  training:
    max_epochs: 200
    early_stopping:
      enable: true
      patience: 10
