id: Object_Detection_DFine_X
name: DFINE-X

description: "D-FINE is a powerful real-time object detector that redefines the bounding box regression task in DETRs as Fine-grained Distribution Refinement (FDR) and introduces Global Optimal Localization Self-Distillation (GO-LSD), achieving outstanding performance without introducing additional inference and training costs."
stats:
  gigaflops: 202
  trainable_parameters: 240
  quality_index:  # scores range from 0 (bad) to 3 (excellent)
    accuracy: 3
    training_time: 1
    inference_speed: 1

hyperparameters:
  training:
    learning_rate: 0.00025
