---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
data:
  server.sh: |-
    #!/bin/bash
    set -xe

    echo listeners=${KAFKA_LISTENERS} >> "${KAFKA_CONF_FILE}"
    echo advertised.listeners=${KAFKA_ADVERTISED_LISTENERS} >> "${KAFKA_CONF_FILE}"
    echo listener.security.protocol.map=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} >> "${KAFKA_CONF_FILE}"
    echo allow.everyone.if.no.acl.found=${KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND} >> "${KAFKA_CONF_FILE}"
    echo authorizer.class.name=${KAFKA_AUTHORIZER_CLASS_NAME} >> "${KAFKA_CONF_FILE}"
    echo auto.create.topics.enable=${KAFKA_AUTO_CREATE_TOPICS_ENABLE} >> "${KAFKA_CONF_FILE}"
    echo controller.listener.names=${KAFKA_CONTROLLER_LISTENER_NAMES} >> "${KAFKA_CONF_FILE}"
    echo controller.quorum.voters=${KAFKA_CONTROLLER_QUORUM_VOTERS} >> "${KAFKA_CONF_FILE}"
    echo default.replication.factor=${KAFKA_DEFAULT_REPLICATION_FACTOR} >> "${KAFKA_CONF_FILE}"
    echo delete.topic.enable=${KAFKA_DELETE_TOPIC_ENABLE} >> "${KAFKA_CONF_FILE}"
    echo inter.broker.listener.name=${KAFKA_INTER_BROKER_LISTENER_NAME} >> "${KAFKA_CONF_FILE}"
    echo log.retention.check.intervals.ms=${KAFKA_LOG_RETENTION_CHECK_INTERVALS_MS} >> "${KAFKA_CONF_FILE}"
    echo message.max.bytes=${KAFKA_MESSAGE_MAX_BYTES} >> "${KAFKA_CONF_FILE}"
    echo node.id=${KAFKA_NODE_ID} >> "${KAFKA_CONF_FILE}"
    echo process.roles=${KAFKA_PROCESS_ROLES} >> "${KAFKA_CONF_FILE}"
    echo sasl.enabled.mechanisms=${KAFKA_SASL_ENABLED_MECHANISMS} >> "${KAFKA_CONF_FILE}"
    echo sasl.mechanism.controller.protocol=${KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL} >> "${KAFKA_CONF_FILE}"
    echo sasl.mechanism.inter.broker.protocol=${KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL} >> "${KAFKA_CONF_FILE}"
    echo super.users=${KAFKA_SUPER_USERS} >> "${KAFKA_CONF_FILE}"
    echo listener.name.controller.sasl.enabled.mechanisms=${KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL} >> "${KAFKA_CONF_FILE}"
    echo listener.name.controller.plain.sasl.jaas.config="org.apache.kafka.common.security.plain.PlainLoginModule required username=\"controller_user\" password=\"test\" user_controller_user=\"test\";" >> "${KAFKA_CONF_FILE}"
    read -r -a sasl_mechanisms_arr <<<"$(tr ',' ' ' <<<"$KAFKA_SASL_ENABLED_MECHANISMS")"
    read -r -a users <<<"$(tr ',;' ' ' <<<"$KAFKA_CLIENT_USERS")"
    read -r -a passwords <<<"$(tr ',;' ' ' <<<"$KAFKA_CLIENT_PASSWORDS")"
    # Configure JAAS for each SASL mechanism
    # ref: https://docs.confluent.io/platform/current/kafka/authentication_sasl/index.html
    for sasl_mechanism in "${sasl_mechanisms_arr[@]}"; do
        jaas_content=()
        # For PLAIN mechanism, only the first username will be used
        if [[ "$sasl_mechanism" = "PLAIN" ]]; then
            jaas_content=("org.apache.kafka.common.security.plain.PlainLoginModule required")
            jaas_content+=(
                "username=\"${KAFKA_INTER_BROKER_USER}\""
                "password=\"${KAFKA_INTER_BROKER_PASSWORD}\""
            )
            users+=("$KAFKA_INTER_BROKER_USER")
            passwords+=("$KAFKA_INTER_BROKER_PASSWORD")
            for ((i = 0; i < ${#users[@]}; i++)); do
                jaas_content+=("user_${users[i]}=\"${passwords[i]}\"")
            done
            # Add semi-colon to the last element of the array
            jaas_content[${#jaas_content[@]} - 1]="${jaas_content[${#jaas_content[@]} - 1]};"
        elif [[ "$sasl_mechanism" =~ SCRAM ]]; then
            jaas_content=(
                "org.apache.kafka.common.security.scram.ScramLoginModule required"
                "username=\"${KAFKA_INTER_BROKER_USER}\""
                "password=\"${KAFKA_INTER_BROKER_PASSWORD}\";"
            )
        fi
        sasl_mechanism_lower="$(echo "$sasl_mechanism" | tr '[:upper:]' '[:lower:]')"
        echo "listener.name.client.${sasl_mechanism_lower}.sasl.jaas.config=${jaas_content[*]}" >> "${KAFKA_CONF_FILE}"
    done

  init.sh: |-
    #!/bin/bash
    set -xe

    args=("--config" "${KAFKA_CONF_FILE}" "--ignore-formatted")
    echo "Initializing KRaft cluster with ID: ${KAFKA_CLUSTER_ID}"
    args+=("--cluster-id=${KAFKA_CLUSTER_ID}")
    echo "Adding KRaft SCRAM users at storage bootstrap"
    read -r -a users <<<"$(tr ',;' ' ' <<<"${KAFKA_CLIENT_USERS}")"
    read -r -a passwords <<<"$(tr ',;' ' ' <<<"${KAFKA_CLIENT_PASSWORDS}")"
    if [[ "${KAFKA_SASL_ENABLED_MECHANISMS}" == *SCRAM-SHA-256* ]]; then
      for ((i = 0; i < ${#users[@]}; i++)); do
        args+=("--add-scram" "SCRAM-SHA-256=[name=${users[i]},password=${passwords[i]}]")
      done
    fi
    if [[ "${KAFKA_SASL_ENABLED_MECHANISMS}" == *SCRAM-SHA-512* ]]; then
      for ((i = 0; i < ${#users[@]}; i++)); do
        args+=("--add-scram" "SCRAM-SHA-512=[name=${users[i]},password=${passwords[i]}]")
      done
    fi
    echo "Formatting storage directories to add metadata..."
    "${KAFKA_HOME}/bin/kafka-storage.sh" format "${args[@]}"

  kafka_jaas.sh: |-
    #!/bin/bash
    set -xe

    echo "KafkaServer {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username=admin
        password=\"${KAFKA_ADMIN_PASSWORD}\"
        user_admin=\"${KAFKA_ADMIN_PASSWORD}\"
        user_broker=\"${KAFKA_ADMIN_PASSWORD}\";
    };" > /opt/kafka/config/kafka_server_jaas.conf
