---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "kafka.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "kafka.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "kafka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kafka.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kafka.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ if .Values.image.repository }}{{ .Values.image.repository }}/{{ end }}{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
            - >
              /etc/kafka/scripts/kafka_jaas.sh &&
              /etc/kafka/docker/run
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KAFKA_CLIENT_USERS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}-kafka-jaas
                  key: client-users
            - name: KAFKA_CLIENT_PASSWORDS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}-kafka-jaas
                  key: client-passwords
            - name: KAFKA_INTER_BROKER_USER
              valueFrom:
                secretKeyRef:
                  key: inter-broker-user
                  name: impt-kafka-jaas
            - name: KAFKA_INTER_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: inter-broker-password
                  name: impt-kafka-jaas
            - name: KAFKA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}-kafka-jaas
                  key: system-user-password
            - name: KAFKA_NODE_ID
              value: {{ .Values.kraft.nodeId | quote }}
            - name: KAFKA_PROCESS_ROLES
              value: {{ .Values.kraft.roles | quote }}
            - name: KAFKA_SUPER_USERS
              value: "User:admin"
            - name: KAFKA_CLUSTER_ID
              value: {{ .Values.kraft.clusterId | quote }}
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:SASL_PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT"
            - name: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
              value: "true"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "SASL_PLAINTEXT://$(MY_POD_NAME).impt-kafka-headless.impt.svc.cluster.local:9092"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "0@$(MY_POD_NAME).impt-kafka-headless.impt.svc.cluster.local:9093"
            - name: KAFKA_LISTENERS
              value: 'CONTROLLER://:9093,SASL_PLAINTEXT://:9092'
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: 'SASL_PLAINTEXT'
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: 'CONTROLLER'
            - name: CLUSTER_ID
              value: '4L6g3nShT-eMCtK--X86sw'
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR
              value: "1"
            - name: KAFKA_LOG_DIRS
              value: '/tmp/kraft-combined-logs'
            - name: KAFKA_SASL_ENABLED_MECHANISMS
              value: "PLAIN"
            - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
              value: 'PLAIN'
            - name: KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL
              value: 'PLAIN'
            - name: KAFKA_HOME
              value: /opt/kafka
            - name: KAFKA_CONF_FILE
              value: /opt/kafka/config/server.properties
            - name: KAFKA_OPTS
              value: "-Djava.security.auth.login.config=/opt/kafka/config/kafka_server_jaas.conf"
            - name: KAFKA_AUTHORIZER_CLASS_NAME
              value: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "false"
          ports:
          - name: broker
            containerPort: {{ .Values.service.broker }}
          - name: controller
            containerPort: {{ .Values.service.controller }}
          volumeMounts:
            - name: config
              mountPath: /etc/kafka/scripts/
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: {{ include "kafka.fullname" . }}
            defaultMode: 365
        - name: tmp
          emptyDir: {}
