{
 "title": "Model training time",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "organization_id",
    "label": "Organization ID",
    "query": {
     "query": "label_values(geti_application_models_training_duration_seconds_total,organization_id)"
    }
   },
   {
    "name": "task_type",
    "label": "Task Type",
    "query": {
     "query": "label_values(geti_application_models_training_duration_seconds_total,task_type)"
    }
   },
   {
    "name": "model_architecture",
    "label": "Model Architecture",
    "query": {
     "query": "label_values(geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\"},model_architecture)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Min. model training time",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. model training time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max. model training time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total model training time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min. train job duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. train job duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max. train job duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total train job duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of trainings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of successful trainings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of cancelled trainings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=\"CANCELLED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of failed trainings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=\"FAILED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min. dataset size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average dataset size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max. dataset size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total FAILED/CANCELLED train job duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"FAILED|CANCELLED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of trainings per task type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average model training time per task type (in s)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of trainings per model architecture",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average model training time per model architecture (in s)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "geti_application_models_training_duration_seconds_total{task_type=~\"$task_type\", model_architecture=~\"$model_architecture\", job_status=~\"SUCCEEDED\", organization_id=~\"$organization_id\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}