{
 "title": "OpenTelemetry Collector",
 "description": "Provides information about the status of the OpenTelemetry Collector",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "receiver", "label": "receiver", "query": { "query": "label_values(otelsvc_receiver)" } },
   { "name": "exporter", "label": "exporter", "query": { "query": "label_values(otelsvc_exporter)" } },
   { "name": "processor", "label": "processor", "query": { "query": "label_values(processor)" } }
  ]
 },
 "panels": [
  {
   "title": "Receivers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Received Logs",
   "type": "timeseries",
   "description": "Rate of received logs per second",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_log_records{receiver=~\"$receiver\"}[5m])) by (receiver)",
     "legendFormat": "{{receiver}} accepted /sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_log_records{receiver=~\"$receiver\"}[5m])) by (receiver)",
     "legendFormat": "{{ receiver }} refused / sec"
    }
   ]
  },
  {
   "title": "Received Metrics",
   "type": "timeseries",
   "description": "Rate of received metrics per second",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points{receiver=~\"$receiver\"}[5m])) by (receiver)",
     "legendFormat": "{{receiver}} accepted /sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points{receiver=~\"$receiver\"}[5m])) by (receiver)",
     "legendFormat": "{{ receiver }} refused / sec"
    }
   ]
  },
  {
   "title": "Received Spans",
   "type": "timeseries",
   "description": "Rate of received spans per second",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{receiver=~\"$receiver\"}[5m])) by (receiver)",
     "legendFormat": "{{receiver}} spans accepted / sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{receiver=~\"$receiver\"}[5m])) by (receiver)",
     "legendFormat": "{{ receiver }} spans refused /sec"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processed Logs",
   "type": "timeseries",
   "description": "Rate of processed logs per second",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_accepted_log_records{processor=~\"$processor\"}[5m])) by (processor)",
     "legendFormat": "{{exporter}} accepted / sec"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_log_records{processor=~\"$processor\"}[5m])) by (processor)",
     "legendFormat": "{{ exporter }} refused /sec"
    },
    {
     "expr": "sum(rate(otelcol_processor_dropped_log_records{processor=~\"$processor\"}[5m])) by (processor)",
     "legendFormat": "{{ exporter }} dropped /sec"
    }
   ]
  },
  {
   "title": "Processed Metrics",
   "type": "timeseries",
   "description": "Rate of processed metrics per second",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_accepted_metric_points{processor=~\"$processor\"}[5m])) by (processor)",
     "legendFormat": "{{exporter}} accepted / sec"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_metric_points{processor=~\"$processor\"}[5m])) by (processor)",
     "legendFormat": "{{ exporter }} refused /sec"
    },
    {
     "expr": "sum(rate(otelcol_processor_dropped_metric_points{processor=~\"$processor\"}[5m])) by (processor)",
     "legendFormat": "{{ exporter }} dropped /sec"
    }
   ]
  },
  {
   "title": "Processed Spans",
   "type": "timeseries",
   "description": "Rate of processed spans per second",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_accepted_spans{processor=~\"$processor\"}[5m])) by (processor)",
     "legendFormat": "{{exporter}} accepted / sec"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_spans{processor=~\"$processor\"}[5m])) by (processor)",
     "legendFormat": "{{ exporter }} refused /sec"
    },
    {
     "expr": "sum(rate(otelcol_processor_dropped_spans{processor=~\"$processor\"}[5m])) by (processor)",
     "legendFormat": "{{ exporter }} dropped /sec"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Exported Logs",
   "type": "timeseries",
   "description": "Rate of exported logs per second",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_log_records{exporter=~\"$exporter\"}[5m])) by (exporter)",
     "legendFormat": "{{exporter}} sent /sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_log_records{exporter=~\"$exporter\"}[5m])) by (exporter)",
     "legendFormat": "{{ exporter }} failed / sec"
    }
   ]
  },
  {
   "title": "Exported Metrics",
   "type": "timeseries",
   "description": "Rate of exported metrics per second",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{exporter=~\"$exporter\"}[5m])) by (exporter)",
     "legendFormat": "{{exporter}} sent /sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points{exporter=~\"$exporter\"}[5m])) by (exporter)",
     "legendFormat": "{{ exporter }} failed / sec"
    }
   ]
  },
  {
   "title": "Exported Spans",
   "type": "timeseries",
   "description": "Rate of exported spans per second",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{exporter=~\"$exporter\"}[5m])) by (exporter)",
     "legendFormat": "{{exporter}} sent / sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{exporter=~\"$exporter\"}[5m])) by (exporter)",
     "legendFormat": "{{ exporter }} failed /sec"
    }
   ]
  }
 ]
}