{
 "title": "Project and Model Totals",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Projects per type",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(project_type) (geti_application_projects_total_gauge)",
     "legendFormat": "{{project_type}}"
    }
   ]
  },
  {
   "title": "Models per task type",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(task_type) (geti_application_models_total_gauge_task_type)",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "Models per task type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(task_type) (geti_application_models_total_gauge_task_type)",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "Projects per type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(project_type) (geti_application_projects_total_gauge)",
     "legendFormat": "{{project_type}}"
    }
   ]
  },
  {
   "title": "Models per task type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(task_type) (geti_application_models_total_gauge_task_type)",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "Projects per type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(project_type) (geti_application_projects_total_gauge)",
     "legendFormat": "{{project_type}}"
    }
   ]
  },
  {
   "title": "Models per architecture",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(model_architecture) (geti_application_models_total_gauge_architecture)",
     "legendFormat": "{{model_architecture}}"
    }
   ]
  }
 ]
}