{
 "title": "Access log - Resource microservice",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod_name",
    "label": "Pod name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Product info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get product info (GET /api/v1/product_info)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/product_info` [1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get user settings (GET /api/v1/user_settings)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/user_settings` [1m]))"
      }
     ]
    },
    {
     "title": "Store user settings (POST /api/v1/user_settings)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 2 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `POST` | path =~ `/api/v1/user_settings` [1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Workspaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get all workspaces (GET /api/v1/workspaces)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces` [1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Projects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get all projects (GET /api/v1/workspaces/.*/projects)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects` [1m]))"
      }
     ]
    },
    {
     "title": "Create project (POST /api/v1/workspaces/.*/projects)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `POST` | path =~ `/api/v1/workspaces/.{24}/projects` [1m]))"
      }
     ]
    },
    {
     "title": "Get project (GET /api/v1/workspaces/.*/projects/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}` [1m]))"
      }
     ]
    },
    {
     "title": "Update project (PUT /api/v1/workspaces/.*/projects/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `PUT` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}` [1m]))"
      }
     ]
    },
    {
     "title": "Get project thumbnail (GET /api/v1/workspaces/.*/projects/.*/thumbnail)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/thumbnail` [1m]))"
      }
     ]
    },
    {
     "title": "Delete project (DELETE /api/v1/workspaces/.*/projects/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `DELETE` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}` [1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Datasets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get datasets (GET /api/v1/workspaces/.*/projects/.*/datasets)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets` [1m]))"
      }
     ]
    },
    {
     "title": "Create dataset (POST /api/v1/workspaces/.*/projects/.*/datasets)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 5 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `POST` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets` [1m]))"
      }
     ]
    },
    {
     "title": "Get dataset (POST /api/v1/workspaces/.*/projects/.*/datasets/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}` [1m]))"
      }
     ]
    },
    {
     "title": "Update dataset (PUT /api/v1/workspaces/.*/projects/.*/datasets/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 5 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `PUT` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}` [1m]))"
      }
     ]
    },
    {
     "title": "Delete dataset (DELETE /api/v1/workspaces/.*/projects/.*/datasets/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `DELETE` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}` [1m]))"
      }
     ]
    },
    {
     "title": "Get dataset statistics (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/statistics)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/statistics` [1m]))"
      }
     ]
    },
    {
     "title": "Get dataset (training revision) (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/training_revisions/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/training_revisions/.*` [1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Media",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get media (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/media)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media` [1m]))"
      }
     ]
    },
    {
     "title": "Query media (POST /api/v1/workspaces/.*/projects/.*/datasets/.*/media:query)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method =~ `POST` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media%3Aquery` [1m]))"
      }
     ]
    },
    {
     "title": "Get training revision media (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/training_revisions/.*/media)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method =~ `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/training_revisions/.{24}/media` [1m]))"
      }
     ]
    },
    {
     "title": "Query training revision media (POST /api/v1/workspaces/.*/projects/.*/datasets/.*/training_revisions/.*/media:query)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 23 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method =~ `POST` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/training_revisions/.{24}/media%3Aquery` [1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Images",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get images (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/media/images)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/images` [1m]))"
      }
     ]
    },
    {
     "title": "Upload image (POST /api/v1/workspaces/.*/projects/.*/datasets/.*/media/images)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 7 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `POST` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/images` [1m]))"
      }
     ]
    },
    {
     "title": "Get image (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/media/images/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/images/.{24}` [1m]))"
      }
     ]
    },
    {
     "title": "Delete image (DELETE /api/v1/workspaces/.*/projects/.*/datasets/.*/media/images/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `DELETE` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/images/.{24}` [1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Videos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get videos (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/media/videos)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/videos` [1m]))"
      }
     ]
    },
    {
     "title": "Upload video (POST /api/v1/workspaces/.*/projects/.*/datasets/.*/media/videos)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `POST` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/videos` [1m]))"
      }
     ]
    },
    {
     "title": "Get video (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/media/videos/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/videos/.{24}` [1m]))"
      }
     ]
    },
    {
     "title": "Delete video (DELETE /api/v1/workspaces/.*/projects/.*/datasets/.*/media/videos/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `DELETE` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/videos/.{24}` [1m]))"
      }
     ]
    },
    {
     "title": "Get video (display type) (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/media/videos/.*/display/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/videos/.{24}/display/.*` [1m]))"
      }
     ]
    },
    {
     "title": "Get video frame (display type) (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/media/videos/.*/frames/.*/display/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/videos/.{24}/frames/.*/display/.*` [1m]))"
      }
     ]
    },
    {
     "title": "Query video (POST /api/v1/workspaces/.*/projects/.*/datasets/.*/media/videos/.*:query)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `POST` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/videos/.{24}%3Aquery` [1m]))"
      }
     ]
    },
    {
     "title": "Query video (training revision) (POST /api/v1/workspaces/.*/projects/.*/datasets/.*/training_revisions/.*/media/videos/.*:query)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `POST` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/training_revisions/.{24}/media/videos/.{24}%3Aquery` [1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Media score",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query media score (POST /api/v1/workspaces/.*/projects/.*/datasets/.*_score/tests/.*/results:query)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `POST` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}_score/tests/.{24}/results%3Aquery` [1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Code deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prepare code deployment (POST /api/v1/workspaces/.*/projects/.*/code_deployments:prepare)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `POST` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/code_deployments:prepare` [1m]))"
      }
     ]
    },
    {
     "title": "Get code deployment status (GET /api/v1/workspaces/.*/projects/.*/code_deployments/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 28 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/code_deployments/.{24}` [1m]))"
      }
     ]
    },
    {
     "title": "Download code deployment (GET /api/v1/workspaces/.*/projects/.*/code_deployments/.*/download)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/code_deployments/.{24}/download` [1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Image annotations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Create image annotation (POST /api/v1/workspaces/.*/projects/.*/datasets/.*/media/images/.*/annotations)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `POST` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/images/.{24}/annotations` [1m]))"
      }
     ]
    },
    {
     "title": "Get image annotation (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/media/images/.*/annotations/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/images/.{24}/annotations/.{24}` [1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Video annotations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Create video frame annotation (POST /api/v1/workspaces/.*/projects/.*/datasets/.*/media/videos/.*/frames/.*/annotations)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `POST` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/videos/.{24}/frames/.*/annotations` [1m]))"
      }
     ]
    },
    {
     "title": "Get video frame annotation (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/media/videos/.*/frames/.*/annotations/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/videos/.{24}/frames/.*/annotations/.{24}` [1m]))"
      }
     ]
    },
    {
     "title": "Get video annotation (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/media/videos/.*/annotations/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/videos/.{24}/annotations/.{24}` [1m]))"
      }
     ]
    },
    {
     "title": "Submit video range annotations (POST /api/v1/workspaces/.*/projects/.*/datasets/.*/media/videos/.*/range_annotation)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `POST` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/videos/.{24}/range_annotation` [1m]))"
      }
     ]
    },
    {
     "title": "Get video range annotations (GET /api/v1/workspaces/.*/projects/.*/datasets/.*/media/videos/.*/range_annotation)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/datasets/.{24}/media/videos/.{24}/range_annotation` [1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Model",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get model groups (GET /api/v1/workspaces/.*/projects/.*/model_groups)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/model_groups` [1m]))"
      }
     ]
    },
    {
     "title": "Get model group (GET /api/v1/workspaces/.*/projects/.*/model_groups/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 13 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/model_groups/.{24}` [1m]))"
      }
     ]
    },
    {
     "title": "Activate model group (POST /api/v1/workspaces/.*/projects/.*/model_groups/.*:activate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `POST` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/model_groups/.{24}%3Aactivate` [1m]))"
      }
     ]
    },
    {
     "title": "Get model (GET /api/v1/workspaces/.*/projects/.*/model_groups/.*/models/.*)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 13 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/model_groups/.{24}/models/.{24}` [1m]))"
      }
     ]
    },
    {
     "title": "Get model statistics (GET /api/v1/workspaces/.*/projects/.*/model_groups/.*/models/.*/statistics)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/model_groups/.{24}/models/.{24}/statistics` [1m]))"
      }
     ]
    },
    {
     "title": "Export model (GET /api/v1/workspaces/.*/projects/.*/model_groups/.*/models/.*/export)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 22 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/model_groups/.{24}/models/.{24}/export` [1m]))"
      }
     ]
    },
    {
     "title": "Export optimized model (GET /api/v1/workspaces/.*/projects/.*/model_groups/.*/models/.*/optimized_models/.*/export)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum by(k8s_pod_name, response_code) (count_over_time({exporter=~\".+\", k8s_container_name=\"resource\", k8s_pod_name=~\"$pod_name\"} |= `uvicorn.access` | json | line_format `{{.body}}` | regexp `.{27} \\[.*\\] \\[.*\\]\\: .*? \\- \\\"(?P<method>.*?) (?P<path>.*?) HTTP\\/1.1\\\" (?P<response_code>\\d{3})` | method = `GET` | path =~ `/api/v1/workspaces/.{24}/projects/.{24}/model_groups/.{24}/models/.{24}/optimized_models/.{24}/export` [1m]))"
      }
     ]
    }
   ]
  }
 ]
}