- apiGroups: [""]
  resources: ["namespaces", "configmaps"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "patch", "update"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "list", "watch", "get"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["create"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "create", "list", "watch"]
- apiGroups: ["helm.cattle.io"]
  resources: ["helmcharts"]
  verbs: ["create", "patch", "update"]
