---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seaweed-fs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweed-fs.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 8 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "seaweed-fs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweed-fs.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "seaweed-fs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweed-fs.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "seaweed-fs.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "seaweed-fs.fullname" . }}
    namespace: {{ .Release.Namespace }}
