FROM python:3.10-slim-bookworm@sha256:66a6e8a211a02794515d4e1aa1970fc037ec4dde1429395e1321bdd63af01256 AS base

FROM base AS build

ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy

# Disable Python downloads, because we want to use the system interpreter
# across both images.
ENV UV_PYTHON_DOWNLOADS=0

# need to install the system dependencies for the python-ldap
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    libldap2-dev \
    libsasl2-dev \
    libssl-dev

# Copy the service dependencies
COPY --link --from=libs . libs
COPY --link --from=platform_libs . platform/libs

WORKDIR /platform/services/user_directory

COPY --link --from=ghcr.io/astral-sh/uv:0.6.12@sha256:515b886e8eb99bcf9278776d8ea41eb4553a794195ef5803aa7ca6258653100d /uv /bin/uv

COPY --link app .

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-dev --no-editable

FROM base AS runtime

# need to install the system dependencies for the python-ldaplibraries
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libsasl2-2 \
    libldap-2.5-0 && \
    apt clean all && \
    rm -rf /var/cache/apt/* && \
    useradd -l -u 10001 non-root && \
	pip3 uninstall -y setuptools pip wheel && \
    rm -rf /root/.cache/pip

USER non-root

# Copy the application from the builder
COPY --link --from=build --chown=10001 /platform/services/user_directory /platform/services/user_directory
COPY --link entrypoint.sh /platform/services/user_directory
COPY --link logconfig.ini /platform/services/user_directory

# Place executables in the environment at the front of the path
ENV PATH="/platform/services/user_directory/.venv/bin:$PATH"

WORKDIR /platform/services/user_directory
ENTRYPOINT [ "./entrypoint.sh" ]
