# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

include ../../../Makefile.shared-python

COMPONENT_NAME = install-upgrade

static-code-analysis-default:
	@echo "Not applicable"

build-chart-default:
	@echo "Not applicable"

test-component:
	@echo "Not applicable"

test-integration:
	@echo "Not applicable"

publish-chart:
	@echo "Not applicable"
