---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-kafka-topics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-provisioning.labels" . | nindent 4 }}
data:
  topics.properties: |-
    {{- printf "%s" "# topic, replicationFactor, numPartitions, config (list)"  | nindent 4 }}
    {{- range $topic := .Values.provisioning.topics }}
    {{- include "kafka.topic.line" (dict "topic" $topic "context" $)  | nindent 4 -}}
    {{- end }}

  acl.properties: |-
    {{- printf "%s" "# topic, user, operations (list)"   | nindent 4}}
    {{- range $acl := .Values.provisioning.acls }}
    {{- include "kafka.acl.line" (dict "acl" $acl "context" $)  | nindent 4 -}}
    {{- end }}
