# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

LOCAL_PORT = 9200
SERVICE_PORT = 9200
SERVICE_NAME = "geti-controller"
GETI_CONTROLLER_NAMESPACE = "default"
GETI_CONTROLLER_CHART_NAME = "geti-controller-chart"
