# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

include ../Makefile.shared-builders

BUILDER_IMAGE_NAME = python-builder
BUILDER_TAG = v1.0.2
DOCKER_IMAGE_DESCRIPTION := Python builder image for Geti
