global:
  weights_url: "https://storage.geti.intel.com/weights"
  docker_namespace: "geti"
  proxy:
    enabled: false
    http_proxy: ""
    https_proxy: ""
    no_proxy: ""
  kubectl:
    registry: registry.k8s.io
    repository: kubectl
    name: v1.31.12
