include ../../Makefile.shared

# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

COMPONENT_NAME := dex-templates-init-copy
DOCKER_IMAGE_DESCRIPTION := Dex templates for Geti

lint-chart:
	@echo "Running chart linter for component: ${COMPONENT_NAME} NOT IMPLEMENTED"

build-chart:
	@echo "Publishing chart for component: ${COMPONENT_NAME} NOT IMPLEMENTED"

publish-chart:
	@echo "Publishing chart for component: ${COMPONENT_NAME} NOT IMPLEMENTED"

test-unit:
	@echo "Not applicable"

test-component:
	@echo "Not applicable"

test-integration:
	@echo "Not applicable"

static-code-analysis:
	@echo "Not applicable"
