{{ $previous := lookup "rbac.authorization.k8s.io/v1" "ClusterRoleBinding" "" ( include "geti-controller.name" .) }}
{{- if not $previous }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "geti-controller.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "geti-controller.name" . }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ include "geti-controller.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
