{{ $previous := lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" ( include "geti-controller.name" .) }}
{{- if not $previous }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "geti-controller.name" . }}
rules:
{{ .Files.Get "files/rules.yaml" }}
{{- end }}
