{{- if .Values.global.ingress_enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "geti-controller.name" . }}-version
rules:
{{ .Files.Get "files/rules.yaml" -}}
- apiGroups: [""]
  resources: ["pods", "pods/exec"]  # needed for nvidia device plugin communication (different namespace)
  verbs: ["get", "watch", "list"]
{{- end }}
