{{- if .Values.global.ingress_enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "geti-controller.name" . }}-version
subjects:
- kind: ServiceAccount
  name: {{ include "geti-controller.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "geti-controller.name" . }}-version
  apiGroup: rbac.authorization.k8s.io
{{ end }}
