apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configuration.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  tlsCert: "{{ .Values.global.tlsCert }}"
  tlsKey: "{{ .Values.global.tlsKey }}"
stringData:
  login: "{{ .Values.global.login }}"
  passwordHash: "{{ .Values.global.passwordHash }}"
  dataFolder: "{{ .Values.global.dataFolder }}"
