# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE
"""Module containing dict containing supported FEATURE_FLAGS for the platform"""

FEATURE_FLAGS = {
    "FEATURE_FLAG_ACC_SVC_MOD": "false",
    "FEATURE_FLAG_ALLOW_EXTERNAL_KEY_PROJECT_IMPORT": "true",
    "FEATURE_FLAG_AMBIENT_MESH": "false",
    "FEATURE_FLAG_ANALYTICS_WORKFLOW_ID": "true",
    "FEATURE_FLAG_ANOMALY_REDUCTION": "true",
    "FEATURE_FLAG_ASYNCHRONOUS_MEDIA_PREPROCESSING": "true",
    "FEATURE_FLAG_CAMERA_VIDEO_UPLOAD": "false",
    "FEATURE_FLAG_CLASSIFICATION_RANGES": "true",
    "FEATURE_FLAG_CREDIT_SYSTEM": "false",
    "FEATURE_FLAG_DECORD_VIDEO_DECODER": "false",
    "FEATURE_FLAG_FP16_INFERENCE": "true",
    "FEATURE_FLAG_KEYPOINT_DETECTION": "true",
    "FEATURE_FLAG_KEYPOINT_DETECTION_DATASET_IE": "true",
    "FEATURE_FLAG_MAINTENANCE_BANNER": "false",
    "FEATURE_FLAG_MANAGE_USERS": "false",
    "FEATURE_FLAG_MANAGE_USERS_ROLES": "true",
    "FEATURE_FLAG_OBJECT_STORAGE_OP": "true",
    "FEATURE_FLAG_OFFLINE_INSTALLATION": "true",
    "FEATURE_FLAG_OIDC_CIDAAS": "false",
    "FEATURE_FLAG_ORG_QUOTAS": "false",  # can be enabled only if FEATURE_FLAG_CREDIT_SYSTEM is enabled
    "FEATURE_FLAG_OTX_VERSION_SELECTION": "true",
    "FEATURE_FLAG_REQ_ACCESS": "false",
    "FEATURE_FLAG_RETAIN_TRAINING_ARTIFACTS": "false",
    "FEATURE_FLAG_SAAS_REQUIRE_INVITATION_LINK": "true",
    "FEATURE_FLAG_STORAGE_SIZE_COMPUTATION": "true",
    "FEATURE_FLAG_SUPPORT_CORS": "false",
    "FEATURE_FLAG_USER_ONBOARDING": "false",
    "FEATURE_FLAG_VISUAL_PROMPT_SERVICE": "true",
    "FEATURE_FLAG_WORKSPACE_ACTIONS": "false",
    "FEATURE_FLAG_TELEMETRY_STACK": "false",  # Placeholder for future feature flags
    "FEATURE_FLAG_NEW_CONFIGURABLE_PARAMETERS": "true",
    "FEATURE_FLAG_LABELS_REORDERING": "true",
    "FEATURE_FLAG_ANNOTATION_HOLE": "false",
    "FEATURE_FLAG_MIGRATE_VFR_TO_CFR_VIDEOS": "false",
}
