# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

include ../../../Makefile.shared-go

COMPONENT_NAME := auth-proxy

DOCKER_BUILD_CONTEXT := --build-context account_service_client=$(CWD)/libs/grpc_interfaces/src/grpc_interfaces/account_service/go
DOCKER_IMAGE_DESCRIPTION := Authentication Proxy for Geti
