include ../../../Makefile.shared-python

COMPONENT_NAME := auto-train-controller

DOCKER_BUILD_CONTEXT := --build-context libs=../../../libs \
						--build-context iai_core=../../../interactive_ai/libs/iai_core_py \
