# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE
input_stream: "REQUEST:input"
output_stream: "RESPONSE:output"
node {
  calculator: "OpenVINOModelServerSessionCalculator"
  output_side_packet: "SESSION:session"
  node_options: {
    [type.googleapis.com / mediapipe.OpenVINOModelServerSessionCalculatorOptions]: {
      servable_name: "MODEL_NAME_0"
      servable_version: "1"
    }
  }
}
node {
  calculator: "ModelInferRequestImageCalculator"
  input_stream: "REQUEST:input"
  output_stream: "IMAGE:input_image"
}
node {
  calculator: "AnomalyCalculator"
  input_side_packet: "INFERENCE_ADAPTER:session"
  input_stream: "IMAGE:input_image"
  output_stream: "INFERENCE_RESULT:result"
}
node {
  calculator: "SerializationCalculator"
  input_stream: "REQUEST:input"
  input_stream: "INFERENCE_RESULT:result"
  output_stream: "RESPONSE:output"
}
