id: Anomaly_Stfpm
name: STFPM

description: "STFPM uses a student–teacher architecture with multi-scale feature pyramid matching: during training, student features are aligned with teacher outputs across layers; discrepancies at test time highlight anomalies. Due to such operations, this approach achieves accurate and fast pixel-level anomaly detection."
stats:
  gigaflops: 5.6
  trainable_parameters: 2.8
  quality_index:  # scores range from 0 (bad) to 3 (excellent)
    accuracy: 2
    training_time: 2
    inference_speed: 2
