include ../../../Makefile.shared-python

COMPONENT_NAME := visual-prompt
DOCKER_BUILD_CONTEXT := --build-context libs=../../../libs \
						--build-context iai_core=../../../interactive_ai/libs/iai_core_py \
						--build-context media_utils=../../../interactive_ai/libs/media_utils \
