name: BDD style check
on:
  pull_request:
    paths:
      - "interactive_ai/tests/e2e/**"
      - ".github/workflows/bdd-stylecheck.yml"
  merge_group:
    paths:
      - "interactive_ai/tests/e2e/**"
      - ".github/workflows/bdd-stylecheck.yml"

permissions: {}

jobs:
  style-checks:
    name: Style checks
    timeout-minutes: 30
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
        with:
          version: "0.7.13"

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "18.17.0"

      - name: Install swagger-cli and openapi-generator-cli
        run: |
          npm config set registry "http://registry.npmjs.org/"
          npm install -g @apidevtools/swagger-cli
          npm install -g @openapitools/openapi-generator-cli

      - name: Static code analysis
        working-directory: interactive_ai/tests/e2e
        run: |
          openapi-generator-cli version-manager set 7.13.0
          make static-code-analysis
