name: BDD style check
on:
  pull_request:
    paths:
      - "interactive_ai/tests/e2e/**"
      - ".github/workflows/bdd-stylecheck.yml"
  merge_group:
    paths:
      - "interactive_ai/tests/e2e/**"
      - ".github/workflows/bdd-stylecheck.yml"

permissions: {}

jobs:
  style-checks:
    name: Style checks
    timeout-minutes: 30
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          version: "0.7.13"

      - name: Setup Java
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: "18.17.0"

      - name: Install swagger-cli and openapi-generator-cli
        run: |
          npm config set registry "http://registry.npmjs.org/"
          npm install -g @apidevtools/swagger-cli
          npm install -g @openapitools/openapi-generator-cli

      - name: Static code analysis
        working-directory: interactive_ai/tests/e2e
        run: |
          openapi-generator-cli version-manager set 7.13.0
          make static-code-analysis
