# Main CI workflow for the Geti project
#
# This workflow is triggered on various events such as schedule, pull requests, and pushes to the main branch.
# It prepares build metadata, runs tests, builds components, and publishes binaries if required.
# It also generates a summary report of the daily build.
#
# Key Features:
# - Prepares build variables and metadata
# - Runs tests for libraries and components
# - Builds and publishes Docker images and Helm charts
# - Generates a daily build summary report
#
# Process Stages:
# 1. Prepare build metadata
# 2. Run library tests
# 3. Run component tests
# 4. Build and publish web UI
# 5. Build and publish components
# 6. Build platform distribution binaries
# 7. Check status of all builds and generate daily build summary
#
# Inputs:
# - publish_binaries: Enable publishing binaries (default: true)
#

name: Main CI

on:
  schedule:
    - cron: "0 18 * * *"
  merge_group:
    branches:
      - main
      - release**
  pull_request:
    branches:
      - main
      - release**
  push:
    branches:
      - main
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+-RC[0-9]+

  workflow_dispatch:
    inputs:
      publish_binaries:
        description: "Enable publishing binaries"
        type: boolean
        default: true

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {} # No permissions by default on workflow level

jobs:
  get-vars:
    name: Prepare build metadata
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    outputs:
      build_all: ${{ steps.set-vars.outputs.build_all }}
      build_version: "${{ steps.prepare-build-version.outputs.build_version }}"
      platform_version: "${{ steps.prepare-build-version.outputs.platform_version }}"
      publish_binaries: ${{ steps.set-vars.outputs.publish_binaries }}
      components-list: ${{ steps.components-list.outputs.paths_list }}
      filtered-components-list: ${{ steps.filtered-components-list.outputs.filtered-list }}
      libs-list: ${{ steps.libs-list.outputs.paths_list }}
      registry: ${{ steps.set-vars.outputs.registry }}
      sha: ${{ steps.repo-vars.outputs.sha }}
      images_list: ${{ steps.repo-vars.outputs.images_list }}
      umbrella_chart_list: ${{ steps.repo-vars.outputs.umbrella_chart_list }}
      date: ${{ steps.repo-vars.outputs.date }}

    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Prepare build variables
        id: set-vars
        env:
          EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          DISPATCH_PUB: ${{ github.event.inputs.publish_binaries }}
        run: |

          is_build_all_event() {
            [[ "$EVENT_NAME" == "workflow_dispatch" ]] ||
            [[ "$EVENT_NAME" == "schedule" ]];
          }
          is_publish_event() {
            [[ "$EVENT_NAME" == "schedule" ]] ||
            [[ "$EVENT_NAME" == "workflow_dispatch" && "$DISPATCH_PUB" == "true" ]];
          }
          is_tag() { [[ "$GITHUB_REF" == refs/tags/* ]]; }

          # Set defaults
          build_all=false
          publish_binaries=false

          # Override defaults when conditions are met
          (is_build_all_event || is_tag) && build_all=true
          (is_publish_event || is_tag) && publish_binaries=true

          # REGISTRY: use production registry for scheduled runs, else use dev registry
          if [[ "$EVENT_NAME" == "schedule" ]]; then
            registry="ghcr.io/open-edge-platform"
          else
            registry="ghcr.io/open-edge-platform/dev"
          fi

          echo "build_all=$build_all"               >> $GITHUB_OUTPUT
          echo "publish_binaries=$publish_binaries" >> $GITHUB_OUTPUT
          echo "registry=$registry"                 >> $GITHUB_OUTPUT

          echo "build_all=$build_all"
          echo "publish_binaries=$publish_binaries"
          echo "checkout_ref=$GITHUB_REF"
          echo "checkout_sha=$GITHUB_SHA"
          echo "registry=$registry"

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.sha }}

      - name: Get SHA, list images and umbrella charts
        id: repo-vars
        run: |
          sha=$(git rev-parse HEAD)
          image_list=$(REGISTRY=${{ steps.set-vars.outputs.registry }} make list-image | grep ${{ steps.set-vars.outputs.registry }} | jq -R -s -c 'split("\n")[:-1]')
          umbrella_chart_list=$(REGISTRY=${{ steps.set-vars.outputs.registry }} make list-umbrella-chart | grep ${{ steps.set-vars.outputs.registry }} | jq -R -s -c 'split("\n")[:-1]')
          date=$(date +'%d/%m/%Y')

          echo "::group:: Daily promote variables"
          echo "Image List: $image_list"
          echo "Umbrella Chart List: $umbrella_chart_list"
          echo "SHA: $sha"
          echo "Date: $date"
          echo "::endgroup::"

          echo "images_list=$image_list" >> $GITHUB_OUTPUT
          echo "umbrella_chart_list=$umbrella_chart_list" >> $GITHUB_OUTPUT
          echo "sha=$sha" >> $GITHUB_OUTPUT
          echo "date=$date" >> $GITHUB_OUTPUT

      - name: Prepare build version
        id: prepare-build-version
        uses: ./.github/actions/build-version
        with:
          ref: ${{ github.sha }}

      - name: Get changed components dirs
        id: components-list
        uses: ./.github/actions/change-detection
        with:
          path_filter: "./.github/components-path-filters.yml"
          get_all: ${{ fromJSON(steps.set-vars.outputs.build_all) }} # fromJSON is required to cast string to boolean

      - name: Get changed libs dirs
        id: libs-list
        uses: ./.github/actions/change-detection
        with:
          path_filter: "./.github/libs-path-filters.yml"
          get_all: ${{ fromJSON(steps.set-vars.outputs.build_all) }} # fromJSON is required to cast string to boolean

      - name: Filter components (exclude 'web_ui')
        id: filtered-components-list
        run: |
          components=$(echo ${CHANGES} | sed "s/'/\"/g")
          filtered=$(echo $components | jq -c '[.[] | select(. != "web_ui")]')
          echo "::group::Components to run"
          echo $filtered
          echo "::endgroup::"
          echo "filtered-list=$filtered" >> $GITHUB_OUTPUT
        env:
          CHANGES: ${{ steps.components-list.outputs.paths_list }}

  lib_test_workflow:
    name: Lib test workflow
    needs: get-vars
    permissions:
      contents: read
    uses: ./.github/workflows/libs_test.yml
    if: ${{ !contains(needs.get-vars.outputs.libs-list, '[]') }}
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJSON(needs.get-vars.outputs.libs-list) }}
    with:
      component-dir: ${{ matrix.component }}

  component-workflow:
    name: Component workflow
    needs: get-vars
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/component.yml
    if: ${{ !contains(needs.get-vars.outputs.filtered-components-list, '[]') }}
    strategy:
      fail-fast: false
      matrix:
        # The web-ui-workflow will call component-workflow after it succeeds,
        # therefore we filter out the web_ui component here
        component: ${{ fromJSON(needs.get-vars.outputs.filtered-components-list) }}
    with:
      build_version: ${{ needs.get-vars.outputs.build_version }}
      component_dir: ${{ matrix.component }}
      publish_binaries: ${{ fromJSON(needs.get-vars.outputs.publish_binaries) }} # fromJSON is required to cast string to boolean
      registry: ${{ needs.get-vars.outputs.registry }}

  web-ui-workflow:
    name: Web UI workflow
    needs: get-vars
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/web-ui.yml
    if: ${{ contains(needs.get-vars.outputs.components-list, 'web_ui') }}
    with:
      build_version: ${{ needs.get-vars.outputs.build_version }}
      publish_binaries: ${{ fromJSON(needs.get-vars.outputs.publish_binaries) }} # fromJSON is required to cast string to boolean
      registry: ${{ needs.get-vars.outputs.registry }}

  package-distribution-workflow:
    name: Build platform distribution binaries
    needs:
      - get-vars
      - component-workflow
      - web-ui-workflow
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/package-distribution.yaml
    with:
      build_all: ${{ fromJSON(needs.get-vars.outputs.build_all) }} # fromJSON is required to cast string to boolean
      build_version: ${{ needs.get-vars.outputs.build_version }}
      platform_version: ${{ needs.get-vars.outputs.platform_version }}
      publish_binaries: ${{ fromJSON(needs.get-vars.outputs.publish_binaries) }} # fromJSON is required to cast string to boolean
      registry: ${{ needs.get-vars.outputs.registry }}

  success:
    name: Required status checks
    needs:
      - get-vars
      - component-workflow
      - web-ui-workflow
      - package-distribution-workflow
    permissions:
      discussions: write
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() }}
    env:
      CHECKS: ${{ join(needs.*.result, ' ') }}
      BUILD_VERSION: ${{ needs.get-vars.outputs.build_version }}
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      - name: Check
        run: |
          for check in ${CHECKS}; do
            echo "::notice::check=${check}"
            if [[ "$check" != "success" && "$check" != "skipped" ]]; then
              echo "::error ::Required status checks failed. They must succeed before this pull request can be merged."
              exit 1
            fi
          done
      - name: Create Summary with build version
        if: ${{ fromJSON(needs.get-vars.outputs.publish_binaries) }}
        run: |
          echo "## Required status checks passed" >> $GITHUB_STEP_SUMMARY
          echo "All required status checks have passed successfully." >> $GITHUB_STEP_SUMMARY
          echo "Packages published with tag: $BUILD_VERSION" >> $GITHUB_STEP_SUMMARY

      - name: Generate summary report
        if: github.event_name == 'schedule'
        id: msg
        run: |
          echo "## Daily Build Summary" > body.txt
          echo "> NOTE: This version is pre-release software and has not undergone full release qualification. APIs/behavior are subject to change. It is NOT meant to be incorporated into any production software/solution." >> body.txt
          echo "" >> body.txt
          echo "**Published version**: ${{ needs.get-vars.outputs.build_version }}" >> body.txt
          echo "**Installation Guide**: [Installation Using Helm Charts](https://docs.geti.intel.com/docs/user-guide/getting-started/installation/using-helm-charts)" >> body.txt
          echo "" >> body.txt
          echo "Use the following value for the environment variable `version` :" >> body.txt
          echo '```' >> body.txt
          echo "export version=${{ needs.get-vars.outputs.build_version }}" >> body.txt
          echo '```' >> body.txt
          echo "" >> body.txt
          echo "**Umbrella Charts**:" >> body.txt
          UMBRELLA_CHARTS_LIST=$(echo '${{ needs.get-vars.outputs.umbrella_chart_list }}' | jq -r '.[]')
          for CHART in $UMBRELLA_CHARTS_LIST; do
            echo "  - $CHART" >> body.txt
          done
          echo "" >> body.txt
          echo "**Container Images**:" >> body.txt
          CONTAINER_IMAGES_LIST=$(echo '${{ needs.get-vars.outputs.images_list }}' | jq -r '.[]')
          for IMAGE in $CONTAINER_IMAGES_LIST; do
            echo "  - $IMAGE:${{ needs.get-vars.outputs.build_version }}" >> body.txt
          done
          echo "" >> body.txt
          echo "**Source Code**: https://github.com/open-edge-platform/geti/tree/${{ needs.get-vars.outputs.sha }}" >> body.txt
          {
            echo "body<<EOF"
            cat body.txt
            echo "EOF"
          } >> $GITHUB_OUTPUT

          cat body.txt >> $GITHUB_STEP_SUMMARY

      - name: Create discussion
        if: github.event_name == 'schedule'
        id: create-discussion
        uses: octokit/graphql-action@abaeca7ba4f0325d63b8de7ef943c2418d161b93 # v3.0.0
        with:
          query: |
            mutation($repoId: ID!, $categoryId: ID!, $title: String!, $body: String!) {
              createDiscussion(input: {
                repositoryId: $repoId,
                categoryId: $categoryId,
                title: $title,
                body: $body
              }) {
                discussion {
                  url
                }
              }
            }
          variables: |
            repoId: "R_kgDOOXK_2A" # This is the repository ID for open-edge-platform/geti
            categoryId: "DIC_kwDOOXK_2M4Ct5TM" # This is the category ID for "Daily Builds"
            title: "Daily build - ${{ needs.get-vars.outputs.date }}"
            body: ${{ toJSON(steps.msg.outputs.body) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
