name: Package distribution workflow
on:
  workflow_call:
    inputs:
      build_all:
        description: "If the triggering workflow is running in build-all-components mode"
        type: boolean
        required: true
      build_version:
        description: "Specifies the build version to apply to all binaries produced by this workflow"
        type: string
        required: true
      platform_version:
        description: "Specifies the current Geti platform version"
        type: string
        required: true
      publish_binaries:
        description: "Enable pushing Docker images and Helm charts"
        type: boolean
        default: false
      ref:
        description: "The branch, tag or SHA to checkout"
        type: string
        default: ""
      registry:
        description: "The container registry to push images to"
        type: string
        required: true
permissions: {} # No permissions by default on workflow level

jobs:
  package-distribution-workflow:
    name: Build platform distribution binaries
    runs-on: ubuntu-latest
    if: ${{ inputs.build_all }}
    permissions:
      contents: read
      packages: write
    env:
      TAG: ${{ inputs.build_version }}
      PLATFORM_VERSION: ${{ inputs.platform_version }}
      REGISTRY: ${{ inputs.registry }}
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          ref: ${{ inputs.ref || '' }}

      - name: Build umbrella charts
        run: make build-umbrella-chart

      - name: Publish umbrella charts
        if: ${{ inputs.publish_binaries }}
        run: make publish-umbrella-chart

      - name: Build installer binary
        if: ${{ inputs.publish_binaries }}
        working-directory: platform/services/installer
        run: |
          printf "product_version: %s\nproduct_build: %s\n" "$PLATFORM_VERSION" "$TAG" > app/version.yaml
          make build
          tar -czf platform_installer.tar.gz platform_$TAG

      - name: Upload build artifacts
        if: ${{ inputs.publish_binaries }}
        uses: actions/upload-artifact@vea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: platform_installer
          path: platform/services/installer/platform_installer.tar.gz
          retention-days: 14
