name: Security Scans on PR

on:
  pull_request:
    branches:
      - main
      - release**
  merge_group:
    branches:
      - main
      - release**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  zizmor-scan-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Run Zizmor scan
        uses: open-edge-platform/geti-ci/actions/zizmor@3cdaaaa0fc400b63f52f4dbb007fa0b69939e0ab
        with:
          scan-scope: "changed"
          severity-level: "LOW"
          confidence-level: "LOW"
          fail-on-findings: true

  bandit-scan-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Run Bandit scan
        uses: open-edge-platform/geti-ci/actions/bandit@3cdaaaa0fc400b63f52f4dbb007fa0b69939e0ab
        with:
          scan-scope: "changed"
          severity-level: "LOW"
          confidence-level: "LOW"
          config_file: ".github/bandit_config.yml"
          fail-on-findings: true
