name: Syft test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to filter images, e.g. '2.13.0-d90fa913'"
        required: true

permissions: {} # No permissions by default on workflow level

jobs:
  collect-packages-names:
    needs: collect-images-list
    timeout-minutes: 660
    runs-on: ubuntu-latest
    steps:
      - name: syft Scan
        shell: bash
        run: |
          # install Syft

          VERSION=1.38.2
          OS=linux
          ARCH=amd64
          BASE_URL="https://github.com/anchore/syft/releases/download/v${VERSION}"
          curl -sL "${BASE_URL}/syft_${VERSION}_${OS}_${ARCH}.tar.gz" > syft_${VERSION}_${OS}_${ARCH}.tar.gz
          curl -sL "${BASE_URL}/syft_${VERSION}_checksums.txt" | grep -E "syft_${VERSION}_${OS}_${ARCH}\\.tar\\.gz$" > checkSum.txt
          if [ -s checkSum.txt ]; then
            sha256sum -c checkSum.txt
          else
            echo "Checksum file not found or empty"
            exit 1
          fi
          tar -zxvf syft_${VERSION}_${OS}_${ARCH}.tar.gz -C /usr/local/bin/ syft
          echo "Syft $(syft version) installed successfully"
          syft ghcr.io/open-edge-platform/geti/account-service:2.14.0-2bff6fc2
